// Weapon skill ratios (part B) for monster casters. rAthena ~2024 battle.cpp, RENEWAL branch.
import { SkillCalc } from './mob-skill-calc'

/** RE_LVL_DMOD(val) from battle.hpp: skillratio = skillratio * BaseLv / val when BaseLv > 100 */
const lvDmod = (ratio: number, lv: number, val: number) => (lv > 100 ? Math.floor((ratio * lv) / val) : ratio)

const NO_CASE = 'battle.cpp:3911 (no case: default 100)'

export const WEAPON_B: Record<string, SkillCalc> = {
  NPC_FIREBREATH: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4080' },
  NPC_GROUNDATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4069' },
  NPC_GUIDEDATTACK: { ratio: () => 100, src: NO_CASE },
  NPC_HELLJUDGEMENT: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4083' },
  NPC_HOLYATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4073' },
  NPC_ICEBREATH: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4081' },
  NPC_IGNITIONBREAK: {
    ratio: (lv) => 500 * (lv + 1),
    note: 'ratio depends on distance to caster: <2 cells 500*(lv+1)% (shown), <4 cells 250+500*lv%, farther 500*lv%',
    src: 'battle.cpp:4525-4535',
  },
  NPC_LICK: { ratio: () => 100, src: NO_CASE },
  NPC_MENTALBREAKER: { ratio: () => 100, src: NO_CASE },
  NPC_PETRIFYATTACK: { ratio: () => 100, src: NO_CASE },
  NPC_PHANTOMTHRUST: { ratio: () => 100, src: 'battle.cpp:4546 (commented out; no case: default 100)' },
  NPC_PIERCINGATT: { ratio: () => 75, src: 'battle.cpp:4061' },
  NPC_POISON: { ratio: () => 100, src: NO_CASE },
  NPC_POISONATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4072' },
  NPC_POWERUP: { ratio: () => 100, src: NO_CASE },
  NPC_PULSESTRIKE: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4084' },
  NPC_RANDOMATTACK: {
    ratio: (lv) => 100 + 100 * (lv - 1),
    note: 'element is random each cast (rnd()%ELE_ALL)',
    src: 'battle.cpp:4067, 3190',
  },
  NPC_SHIELDBRAKE: { ratio: () => 100, src: NO_CASE },
  NPC_SILENCEATTACK: { ratio: () => 100, src: NO_CASE },
  NPC_SLEEPATTACK: { ratio: () => 100, src: NO_CASE },
  NPC_SPLASHATTACK: { ratio: () => 100, src: NO_CASE },
  NPC_STUNATTACK: { ratio: () => 100, src: NO_CASE },
  NPC_TELEKINESISATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4076' },
  NPC_UNDEADATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4075' },
  NPC_VAMPIRE_GIFT: { ratio: (lv) => 100 + (((lv - 1) % 5) + 1) * 100, src: 'battle.cpp:4491' },
  NPC_WATERATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4068' },
  NPC_WEAPONBRAKER: { ratio: () => 100, src: NO_CASE },
  NPC_WINDATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4071' },
  PA_SHIELDCHAIN: {
    ratio: (lv, c) => 200 + 10 * lv + c.vit + c.str,
    note: 'base damage is the mob BaseATK + ATK2 (shield path for non-players), not normal ATK; forced neutral',
    src: 'battle.cpp:4342, 3581 (base), 3296 (neutral)',
  },
  RA_ARROWSTORM: { ratio: (lv, c) => 225 + 20 * lv + 4 * c.dex, src: 'battle.cpp:4603' },
  RG_BACKSTAP: { ratio: (lv, c) => 150 + 5 * lv + c.agi, src: 'battle.cpp:4090' },
  RG_CLOSECONFINE: { ratio: () => 100, src: NO_CASE },
  RG_INTIMIDATE: { ratio: (lv, c) => 200 + 10 * lv + c.vit, src: 'battle.cpp:4105' },
  RG_RAID: { ratio: (lv, c) => 150 + 10 * lv + c.dex, src: 'battle.cpp:4098' },
  RG_STRIPARMOR: { ratio: () => 100, src: NO_CASE },
  RG_STRIPHELM: { ratio: () => 100, src: NO_CASE },
  RG_STRIPSHIELD: { ratio: () => 100, src: NO_CASE },
  RG_STRIPWEAPON: { ratio: () => 100, src: NO_CASE },
  RK_HUNDREDSPEAR: {
    ratio: (lv, c) => 300 + 75 * lv + 3 * c.agi,
    note: 'target with Soul Curse: 500 + 75*lv + 3*(AGI+DEX)%',
    src: 'battle.cpp:4497',
  },
  RK_IGNITIONBREAK: { ratio: (lv, c) => 210 + 15 * lv + 3 * c.luk, src: 'battle.cpp:4520' },
  RK_PHANTOMTHRUST: { ratio: (lv, c) => 200 + 20 * lv + 2 * c.vit, src: 'battle.cpp:4541' },
  RK_SONICWAVE: { ratio: (lv, c) => 150 + 25 * lv + 2 * c.str, src: 'battle.cpp:4494' },
  RK_WINDCUTTER: { ratio: (lv) => 105 + 5 * lv, src: 'battle.cpp:4509' },
  RL_BANISHING_BUSTER: { ratio: (lv, c) => 200 + 20 * lv + 5 * c.int, src: 'battle.cpp:5074' },
  RL_D_TAIL: { ratio: (lv, c) => 150 + 5 * lv + 2 * c.int, src: 'battle.cpp:5087' },
  RL_FIREDANCE: { ratio: (lv, c) => 180 + 10 * lv + c.dex, src: 'battle.cpp:5065' },
  RL_FIRE_RAIN: {
    ratio: (lv, c) => 250 + 10 * lv + c.str,
    note: '+2*lv% more if the target is Burning, and again if Freezing',
    src: 'battle.cpp:5117',
  },
  RL_HAMMER_OF_GOD: { ratio: (lv, c) => 250 + 20 * lv + 4 * c.vit, src: 'battle.cpp:5112' },
  RL_H_MINE: { ratio: (lv) => 150 + 10 * lv, src: 'battle.cpp:5104' },
  RL_MASS_SPIRAL: { ratio: (lv, c) => 150 + 20 * lv + 3 * c.vit, src: 'battle.cpp:5056' },
  RL_R_TRIP: { ratio: (lv, c) => 110 + 15 * lv + c.str, src: 'battle.cpp:5096' },
  RL_SLUGSHOT: { ratio: (lv, c) => 180 + 20 * lv + 4 * c.str, src: 'battle.cpp:5080' },
  SC_FATALMENACE: { ratio: (lv, c) => 250 + 10 * lv + c.vit, src: 'battle.cpp:4694' },
  SC_TRIANGLESHOT: { ratio: (lv, c) => 230 + 10 * lv + 3 * c.agi, src: 'battle.cpp:4701' },
  SG_MOON_WARM: { ratio: () => 100, src: NO_CASE },
  SJ_NEWMOONKICK: { ratio: (lv, c) => 250 + 30 * lv + 5 * c.agi, src: 'battle.cpp:5198' },
  SJ_PROMINENCEKICK: { ratio: (lv, c) => 220 + 10 * lv + c.vit + c.str, src: 'battle.cpp:5217' },
  SJ_SOLARBURST: { ratio: (lv) => 125 + 5 * lv, src: 'battle.cpp:5210' },
  SL_SMA: { ratio: () => 100, src: NO_CASE },
  SM_BASH: { ratio: (lv, c) => 200 + 25 * lv + c.str, src: 'battle.cpp:3912' },
  SM_ENDURE: { ratio: () => 100, src: NO_CASE },
  SM_MAGNUM: { ratio: (lv) => 100 + 20 * lv, src: 'battle.cpp:3918 (mob: miscflag 1, inner formula)' },
  SN_SHARPSHOOTING: { ratio: (lv) => 300 + 50 * lv, src: 'battle.cpp:4286' },
  SO_EARTHGRAVE: { ratio: (lv, c) => 180 + 20 * lv + 2 * c.dex, src: 'battle.cpp:4554' },
  SP_CURSEEXPLOSION: {
    ratio: (lv, c) => 200 + 25 * lv + 2 * c.luk,
    note: 'target with Soul Curse: 300 + 50*lv + 5*LUK%',
    src: 'battle.cpp:5177',
  },
  SR_DRAGONCOMBO: { ratio: (lv, c) => 200 + 15 * lv + 2 * c.luk, src: 'battle.cpp:4809' },
  SR_EARTHSHAKER: {
    ratio: (lv, c) => lvDmod(400 * lv, c.lv, 100) + 2 * c.str,
    note: 'hidden/cloaked target: 300*lv (x BaseLv/100) + 3*STR%',
    src: 'battle.cpp:4796-4806',
  },
  SR_FALLENEMPIRE: { ratio: (lv, c) => 200 + 30 * lv + 2 * c.luk, src: 'battle.cpp:4812' },
  SR_GATEOFHELL: { ratio: (lv, c) => 200 + 10 * lv + 2 * c.luk, src: 'battle.cpp:4844' },
  SR_KNUCKLEARROW: { ratio: (lv, c) => 200 + 25 * lv + c.str, src: 'battle.cpp:4837' },
  SR_SKYNETBLOW: { ratio: (lv, c) => 200 + 20 * lv + 5 * c.agi, src: 'battle.cpp:4826' },
  ST_FULLSTRIP: { ratio: () => 100, src: NO_CASE },
  TF_BACKSLIDING: { ratio: () => 100, src: NO_CASE },
  TF_POISON: { ratio: () => 100, src: NO_CASE + '; Envenom mastery ATK is player-only (3381)' },
  TF_SPRINKLESAND: { ratio: () => 130, src: 'battle.cpp:4051' },
  TK_HIGHJUMP: { ratio: () => 100, src: NO_CASE },
  TK_JUMPKICK: { ratio: (lv, c) => 200 + 10 * lv + 2 * c.dex, src: 'battle.cpp:4372' },
  WL_EARTHSTRAIN: { ratio: (lv, c) => 200 + 50 * lv + 3 * c.str, src: 'battle.cpp:4559' },
  WM_GREAT_ECHO: { ratio: (lv, c) => lvDmod(250 + 500 * lv, c.lv, 100), src: 'battle.cpp:4877' },
}
