// Weapon skill ratios (part A) for monster casters. rAthena ~2024 battle.cpp, RENEWAL branch.
// Caster is a mob: no sd (pc_checkskill -> 0), no caster status changes.
import { SkillCalc } from './mob-skill-calc'

const DEFAULT = 'no case: default 100'

export const WEAPON_A: Record<string, SkillCalc> = {
  AC_CHARGEARROW: { ratio: () => 150, src: 'battle.cpp:3967' },
  AC_DOUBLE: { ratio: (lv) => 100 + 7 * (lv - 1), src: 'battle.cpp:3953' },
  AC_SHOWER: { ratio: (lv) => 150 + 10 * lv, src: 'battle.cpp:3957' },
  AM_ACIDTERROR: { ratio: (lv, c) => 200 + 25 * lv + 2 * c.int, src: 'battle.cpp:4142' },
  AM_DEMONSTRATION: { ratio: (lv, c) => 150 + 5 * lv + c.int, src: 'battle.cpp:4137' },
  ASC_BREAKER: {
    ratio: (lv, c) => 250 + 25 * lv + 5 * c.int,
    note: '+50% + 2×DEX if target has Jyumonjikiri mark (not modeled)',
    src: 'battle.cpp:4329',
  },
  ASC_METEORASSAULT: { ratio: (lv, c) => 150 + 10 * lv + c.dex, src: 'battle.cpp:4279' },
  AS_CLOAKING: { ratio: () => 100, src: DEFAULT },
  AS_GRIMTOOTH: { ratio: (lv, c) => 130 + 10 * lv + c.luk, src: 'battle.cpp:4032' },
  AS_SONICBLOW: {
    ratio: (lv, c) => 225 + 10 * lv + c.luk,
    note: 'ratio ×1.5 when the target is below 50% HP (depends on current HP, not modeled)',
    src: 'battle.cpp:4040',
  },
  AS_SPLASHER: { ratio: (lv, c) => 200 + 15 * lv + c.vit, src: 'battle.cpp:4320' },
  AS_VENOMDUST: { ratio: () => 100, src: DEFAULT },
  BS_HAMMERFALL: { ratio: () => 100, src: DEFAULT },
  BS_MAXIMIZE: { ratio: () => 100, src: DEFAULT },
  CG_ARROWVULCAN: {
    ratio: (lv, c) => 250 + 10 * lv + c.dex + c.str,
    note: 'ratio ×1.5 when the target is below 50% HP (depends on current HP, not modeled)',
    src: 'battle.cpp:4309',
  },
  CH_CHAINCRUSH: { ratio: (lv, c) => 160 + 5 * lv + c.agi, src: 'battle.cpp:4242' },
  CR_ACIDDEMONSTRATION: {
    ratio: (_lv, c) => Math.floor((100 + c.int) / 5),
    note: 'real ratio is (100 + INT + targetVIT/2) / 5 vs players; target VIT not modeled',
    src: 'battle.cpp:4303',
  },
  CR_AUTOGUARD: { ratio: () => 100, src: DEFAULT },
  CR_DEFENDER: { ratio: () => 100, src: DEFAULT },
  CR_HOLYCROSS: {
    ratio: (lv, c) => 200 + 30 * lv + 2 * c.agi,
    note: '+50% + DEX if target has Jyumonjikiri mark (not modeled)',
    src: 'battle.cpp:4127',
  },
  CR_REFLECTSHIELD: { ratio: () => 100, src: DEFAULT },
  CR_SHIELDBOOMERANG: {
    ratio: (lv, c) => 200 + 20 * lv + c.vit,
    element: () => 'Neutral',
    note: 'base damage is the mob status ATK (batk) + ATK2 instead of the normal ATK roll',
    src: 'battle.cpp:3580, 4117, 3237',
  },
  CR_SHIELDCHARGE: { ratio: (lv, c) => 200 + 15 * lv + c.str, src: 'battle.cpp:4108' },
  DC_THROWARROW: { ratio: (lv) => 130 + lv, src: 'battle.cpp:4221' },
  GC_CLOAKINGEXCEED: { ratio: () => 100, src: DEFAULT },
  GC_COUNTERSLASH: { ratio: (lv, c) => 200 + 10 * lv + c.agi, src: 'battle.cpp:4564' },
  GC_CROSSIMPACT: {
    ratio: (lv, c) => 250 + 15 * lv + c.agi,
    note: 'ratio ×1.5 when the target is above 50% HP (depends on current HP, not modeled)',
    src: 'battle.cpp:4547',
  },
  GC_CROSSRIPPERSLASHER: { ratio: (lv, c) => 150 + 15 * lv + c.vit, src: 'battle.cpp:4580' },
  GC_DARKCROW: { ratio: (lv) => 100 + 50 * (lv - 1), src: 'battle.cpp:4585' },
  GC_ROLLINGCUTTER: { ratio: (lv, c) => 110 + 2 * lv + c.vit, src: 'battle.cpp:4575' },
  GC_VENOMPRESSURE: {
    ratio: (lv, c) => 250 + 40 * lv + 2 * c.int,
    note: '+300 + 80×lv + 4×INT if the target is poisoned (not modeled)',
    src: 'battle.cpp:4567',
  },
  GN_SPORE_EXPLOSION: {
    ratio: (lv, c) => 250 + 20 * lv + 4 * c.int,
    note: '+5×lv if target Burning, +2×INT if target Freezing (not modeled)',
    src: 'battle.cpp:4896',
  },
  HFLI_MOON: {
    ratio: (lv) => 100 + 50 * lv,
    note: '+25×lv each if target Burning / Freezing (not modeled)',
    src: 'battle.cpp:4481',
  },
  KN_AUTOCOUNTER: { ratio: (_lv, c) => 400 + c.vit + c.luk, src: 'battle.cpp:4830' },
  KN_BOWLINGBASH: { ratio: (lv, c) => 160 + 10 * lv + 2 * c.str, src: 'battle.cpp:4024' },
  KN_BRANDISHSPEAR: { ratio: (lv, c) => 250 + 15 * lv + 3 * c.vit, src: 'battle.cpp:3997' },
  KN_CHARGEATK: {
    ratio: () => 100,
    note: '+100% per 3 cells of distance to the target (max +400%); modeled at ≤3 cells',
    src: 'battle.cpp:4466',
  },
  KN_PIERCE: { ratio: (lv) => 110 + 2 * lv, src: 'battle.cpp:3977' },
  KN_SPEARBOOMERANG: { ratio: (lv, c) => 150 + 10 * lv + c.dex, src: 'battle.cpp:3991' },
  KN_SPEARSTAB: {
    ratio: (lv, c) => 150 + 5 * lv + c.str,
    note: 'adds a flat caster current HP / 5 after the ratio (not modeled)',
    src: 'battle.cpp:3986, 5281',
  },
  KN_TWOHANDQUICKEN: { ratio: () => 100, src: DEFAULT },
  KO_HAPPOKUNAI: {
    fixed: () => 5000,
    note: 'non-player caster: base damage is a flat 5000 (ratio 100, no case)',
    src: 'battle.cpp:3607',
  },
  KO_JYUMONJIKIRI: {
    ratio: (lv, c) => 200 + 30 * lv + c.agi,
    note: '+25×lv if target already has Jyumonjikiri mark (not modeled)',
    src: 'battle.cpp:5007',
  },
  LG_BANISHINGPOINT: {
    ratio: (lv, c) => 200 + 30 * lv + 2 * c.agi,
    note: '+50% + DEX if target has Jyumonjikiri mark (not modeled)',
    src: 'battle.cpp:4710',
  },
  LG_CANNONSPEAR: { ratio: (lv, c) => 220 + 30 * lv + 3 * c.agi, src: 'battle.cpp:4707' },
  LG_EARTHDRIVE: { ratio: (lv, c) => 250 + 15 * lv + 2 * c.dex, src: 'battle.cpp:4750' },
  LG_MOONSLASHER: { ratio: (lv) => 110 + lv, src: 'battle.cpp:4734' },
  LG_OVERBRAND: { ratio: (lv, c) => 150 + 2 * lv + c.luk, src: 'battle.cpp:4743' },
  LG_SHIELDPRESS: { ratio: (lv) => 110 + 5 * lv, src: 'battle.cpp:4718' },
  LK_SPIRALPIERCE: { ratio: (lv, c) => 150 + 25 * lv + 2 * c.luk, src: 'battle.cpp:4274 (base 3519)' },
  MC_MAMMONITE: { ratio: (lv, c) => 200 + 30 * lv + 2 * c.dex, src: 'battle.cpp:3925' },
  MH_POISON_MIST: {
    path: 'magic',
    ratio: (lv, c) => Math.floor((200 * lv * c.lv) / 100) + Math.floor(c.dex / 6),
    note: 'the mist unit hits as MAGIC (skill.cpp:15691 BF_MAGIC): ratio applies to MATK, not ATK',
    src: 'battle.cpp:7110',
  },
  MH_STAHL_HORN: { ratio: (lv) => 100 + 50 * lv, src: 'battle.cpp:5038' },
  ML_PIERCE: { ratio: (lv) => 110 + 2 * lv, src: 'battle.cpp:3978' },
  ML_SPIRALPIERCE: { ratio: (lv, c) => 150 + 25 * lv + 2 * c.luk, src: 'battle.cpp:4275 (base 3520)' },
  MO_BLADESTOP: { ratio: () => 100, src: DEFAULT },
  MO_CHAINCOMBO: { ratio: (lv) => 250 + 50 * lv, src: 'battle.cpp:4190' },
  MO_COMBOFINISH: { ratio: (lv, c) => 550 + 50 * lv + c.str, src: 'battle.cpp:4199' },
  MO_EXTREMITYFIST: {
    ratio: () => 100,
    note: 'real ratio is 100 + 2×caster SP (SP not modeled, taken as 0); plus a flat 250 + 150×lv added after the ratio',
    src: 'battle.cpp:4179, 5261',
  },
  MO_FINGEROFFENSIVE: { ratio: (_lv, c) => 110 + c.dex, src: 'battle.cpp:4152' },
  NC_AXEBOOMERANG: {
    ratio: (lv, c) => 160 + 15 * lv + c.vit,
    note: '+3×INT if the target is poisoned (not modeled)',
    src: 'battle.cpp:4670',
  },
  NC_AXETORNADO: { ratio: (lv, c) => 200 + 10 * lv + c.vit, src: 'battle.cpp:4685' },
  NC_COLDSLOWER: { ratio: (lv, c) => 150 + 5 * lv + 3 * c.int, src: 'battle.cpp:4656' },
  NC_PILEBUNKER: { ratio: (lv, c) => 300 + 20 * lv + 2 * c.vit, src: 'battle.cpp:4645' },
  NC_POWERSWING: {
    ratio: (lv, c) => 200 + 10 * lv + 2 * c.vit,
    note: '+2×INT if the target is poisoned (not modeled)',
    src: 'battle.cpp:4675',
  },
  NC_VULCANARM: { ratio: (lv, c) => 150 + 20 * lv + c.luk, src: 'battle.cpp:4650' },
  NJ_KIRIKAGE: { ratio: (lv, c) => 200 + 15 * lv + c.luk, src: 'battle.cpp:4450' },
  NJ_KUNAI: { ratio: (lv, c) => 140 + 20 * lv + 2 * c.dex, src: 'battle.cpp:4460' },
  NPC_BLEEDING: { ratio: () => 100, src: DEFAULT },
  NPC_BLINDATTACK: { ratio: () => 100, src: DEFAULT },
  NPC_BLOODDRAIN: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4077' },
  NPC_COMBOATTACK: { ratio: (lv) => 100 + 25 * lv, src: 'battle.cpp:4064' },
  NPC_CRITICALSLASH: { ratio: () => 100, src: DEFAULT },
  NPC_CRITICALWOUND: { ratio: () => 100, src: DEFAULT },
  NPC_CURSEATTACK: { ratio: () => 100, src: DEFAULT },
  NPC_DARKCROSS: {
    ratio: (lv, c) => 200 + 30 * lv + 2 * c.agi,
    note: '+50% + DEX if target has Jyumonjikiri mark (not modeled)',
    src: 'battle.cpp:4126',
  },
  NPC_DARKNESSATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4074' },
  NPC_DEFENDER: { ratio: () => 100, src: DEFAULT },
  NPC_FIREATTACK: { ratio: (lv) => 100 + 100 * (lv - 1), src: 'battle.cpp:4070' },
}
